doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            identity: App\Common\Infra\Doctrine\Type\IdentityType
            bonus: App\Common\Infra\Doctrine\Type\BonusTypeType
            specialInt: App\Common\Infra\Doctrine\Type\SpecialIntegerType
            money: App\Common\Infra\Doctrine\Type\MoneyType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Department:
                type: yml
                dir: "%kernel.project_dir%/src/Department/Infra/Doctrine/Mapping"
                prefix: App\Department\Domain
            Employee:
                type: yml
                dir: "%kernel.project_dir%/src/Employee/Infra/Doctrine/Mapping"
                prefix: App\Employee\Domain

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
