App\Employee\Domain\Employee:
  type: entity
  repositoryClass: App\Employee\Infra\Doctrine\ORMEmployeeRepository
  table: employees

  id:
    id: { type: identity, length: 36 }
  fields:
    name: { type: string, length: 255 }
    surname: { type: string, length: 255 }
    salary: { type: money, nullable: true, options: { unsigned: true } }
    departmentId: { type: identity, length: 36, nullable: true }
    employmentDate: { type: date_immutable, nullable: false }